// Palette: dark editorial terminal aesthetic
// Single accent: teal #00D4B4 — reads as "encrypted / secure"
// Rule: never more than 1 accent color, zero gradients, zero glow

export const ACCENT = '#00D4B4';
export const ACCENT_DARK = '#00A693'; // for light-mode surfaces

export const COLORS = {
	light: {
		background: '#F8F8F8',
		surface: '#EEEEEE',
		chatBackground: '#F0F5F4',
		primary: ACCENT_DARK,
		accent: ACCENT_DARK,
		text: '#0D0D0D',
		subtext: '#888888',
		inputText: '#0D0D0D',
		inputBackground: '#E8E8E8',
		inputBorder: '#CCCCCC',
		inputBorderFocused: ACCENT_DARK,
		sentBubble: ACCENT_DARK,
		sentText: '#FFFFFF',
		receivedBubble: '#E4E4E4',
		receivedText: '#0D0D0D',
		footerBackground: 'rgba(248,248,248,0.96)',
		titleColor: '#0D0D0D',
		titleColorAndroid: '#0D0D0D',
		emptyStateText: '#AAAAAA',
		timeago: '#AAAAAA',
		iconOnLight: '#0D0D0D',
		helperText: ACCENT_DARK,
		headerTitle: '#FFFFFF',
		headerTitleAndroid: '#FFFFFF',
		headerBackground: '#0D0D0D',
		separator: '#E0E0E0',
		unreadBadge: ACCENT_DARK,
		deleteIcon: '#FF4444',
		chatBubbleShadow: 'rgba(0,0,0,0.06)',
	},
	dark: {
		background: '#0D0D0D',
		surface: '#161616',
		chatBackground: '#111111',
		primary: ACCENT,
		accent: ACCENT,
		text: '#F2F2F2',
		subtext: '#6B6B6B',
		inputText: '#F2F2F2',
		inputBackground: '#1A1A1A',
		inputBorder: '#2A2A2A',
		inputBorderFocused: ACCENT,
		sentBubble: ACCENT,
		sentText: '#0D0D0D',
		receivedBubble: '#1E1E1E',
		receivedText: '#F2F2F2',
		footerBackground: 'rgba(13,13,13,0.97)',
		titleColor: '#F2F2F2',
		titleColorAndroid: '#F2F2F2',
		emptyStateText: '#3A3A3A',
		timeago: '#555555',
		iconOnLight: '#F2F2F2',
		helperText: ACCENT,
		headerTitle: '#F2F2F2',
		headerTitleAndroid: '#F2F2F2',
		headerBackground: '#0D0D0D',
		separator: '#1E1E1E',
		unreadBadge: ACCENT,
		deleteIcon: '#FF4444',
		chatBubbleShadow: 'rgba(0,0,0,0.4)',
	},
};
